#!/bin/bash
#============================
# nginx top
#============================
area=us
if [[ ($# > 0) ]]; then
    area=$1
fi

domain=royal-$area.socialgamenet.com
echo $domain
python director.py $domain
